import React, { useState } from 'react';
import { AlertTriangle, CheckCircle, MapPin, TrendingDown, DollarSign, Info, FileText, Send, X, Shield, Users, Search } from 'lucide-react';

interface DialogMessage {
  type: 'success' | 'warning' | 'info';
  title: string;
  message: string;
  details?: string;
}

export default function ContainmentControl() {
  const [selectedRegion, setSelectedRegion] = useState('Punjab - Amritsar');
  const [selectedDisease, setSelectedDisease] = useState('Late Blight (Potato)');
  const [severity, setSeverity] = useState('High');
  const [dataConfidence, setDataConfidence] = useState(87);
  const [showRecommendation, setShowRecommendation] = useState(false);
  const [dialogMessage, setDialogMessage] = useState<DialogMessage | null>(null);
  const [officerNotes, setOfficerNotes] = useState('');
  const [decisionResult, setDecisionResult] = useState<any>(null);
  const [decisionHistory, setDecisionHistory] = useState<any[]>([]);

  const downloadPDF = () => {
    if (!decisionResult) return;
    
    const content = `
AGRICULTURAL DISEASE CONTAINMENT DECISION REPORT
==============================================
Generated: ${new Date().toLocaleString('en-IN')}

REGION: ${decisionResult.region || 'N/A'}
DISEASE: ${decisionResult.disease || 'N/A'}
SEVERITY: ${decisionResult.severity || 'N/A'}

AI RECOMMENDATION
==================
Action: ${decisionResult.action}
Risk Score: ${decisionResult.risk}
Confidence Level: ${decisionResult.confidence}

Explanation: ${decisionResult.explanation}

---
Report generated by AgriPulseX Decision System
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `decision-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const regions = [
    'Punjab - Amritsar',
    'Maharashtra - Nashik',
    'Karnataka - Bangalore Rural',
    'Uttar Pradesh - Meerut',
    'Gujarat - Anand'
  ];

  const diseases = [
    'Late Blight (Potato)',
    'Powdery Mildew (Grape)',
    'Bacterial Wilt (Tomato)',
    'Yellow Rust (Wheat)',
    'Stem Rot (Paddy)'
  ];

  const handleGenerateRecommendation = async () => {
    try {
      // Clear any existing dialog
      setDialogMessage(null);

      const response = await fetch("http://127.0.0.1:8000/decision", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          region: selectedRegion,
          disease: selectedDisease,
          severity: severity,
          dataConfidence: dataConfidence,
        }),
      });

      if (!response.ok) {
        throw new Error(`Backend error: ${response.status} ${response.statusText}`);
      }

      const data = await response.json();
      console.log("Decision API Response:", data);

      // Store response in state
      setDecisionResult(data);
      setShowRecommendation(true);
      
      // Add to decision history (keep last 3)
      setDecisionHistory(prev => {
        const newHistory = [{
          ...data,
          timestamp: new Date().toLocaleString('en-IN'),
          region: selectedRegion,
          disease: selectedDisease,
          severity: severity
        }, ...prev];
        return newHistory.slice(0, 3);
      });

    } catch (error) {
      console.error("Error calling decision API:", error);
      
      // Show error to user
      setDialogMessage({
        type: 'warning',
        title: 'Unable to Generate Recommendation',
        message: 'Could not connect to the AI decision engine.',
        details: `Error: ${error instanceof Error ? error.message : 'Unknown error'}\n\nPlease ensure:\n• Backend server is running on http://127.0.0.1:8000\n• Network connection is stable\n• Try again in a few moments\n\nIf the problem persists, contact technical support.`
      });
    }
  };

  const handleApproveAndImplement = () => {
    if (!decisionResult) return;
    
    // Get actual dependent farmers count based on selected region
    const dependentFarmers = selectedRegion.includes('Punjab') ? 12450 : 
                            selectedRegion.includes('Maharashtra') ? 15680 :
                            selectedRegion.includes('Karnataka') ? 18920 :
                            selectedRegion.includes('Uttar Pradesh') ? 22340 : 8340;
    
    // Generate dynamic values based on backend response
    const radius = decisionResult.risk >= 0.7 ? 5 : decisionResult.risk >= 0.4 ? 3 : 1;
    const compensationPerFarmer = decisionResult.risk >= 0.7 ? 25000 : decisionResult.risk >= 0.4 ? 18000 : 12000;
    const totalCompensation = (dependentFarmers * compensationPerFarmer) / 10000000; // Convert to crores
    const affectedFarmers = Math.round(dependentFarmers * decisionResult.risk);
    
    setDialogMessage({
      type: 'success',
      title: 'Containment Order Approved & Implemented',
      message: `Targeted containment zone has been successfully established for ${selectedRegion}.`,
      details: `• ${radius}km containment radius activated around outbreak epicenter\n• 14-day containment period with mandatory review\n• All transport permits suspended for affected area\n• Compensation package: ₹${totalCompensation.toFixed(2)} crore approved for ${affectedFarmers.toLocaleString()} farmers\n• Field teams deployed for monitoring and enforcement\n\nOrder ID: CNT-${Date.now()}\nApproved by: Dr. Rajesh Kumar Sharma (DAO-PB-2018-4523)\nTimestamp: ${new Date().toLocaleString('en-IN')}`
    });
  };

  const handleRecommendForReview = () => {
    if (!decisionResult) return;
    
    // Dynamic review time based on risk
    const reviewHours = decisionResult.risk >= 0.7 ? '12-24' : '24-48';
    
    setDialogMessage({
      type: 'warning',
      title: 'Recommendation Escalated for Senior Review',
      message: `Containment recommendation has been forwarded to State Agriculture Commissioner for review.`,
      details: `• Review Level: State Agriculture Commissioner\n• Expected Response: ${reviewHours} hours\n• Review Criteria: Economic impact, regional supply stability, political considerations\n• Additional Data Requested: Crop insurance coverage, alternative market routes\n• Your Notes: "${officerNotes || 'No additional notes provided'}"\n\nReference: REV-${Date.now()}\nEscalated by: Dr. Rajesh Kumar Sharma (DAO-PB-2018-4523)\nTimestamp: ${new Date().toLocaleString('en-IN')}`
    });
  };

  const handleRequestFieldVerification = () => {
    if (!decisionResult) return;
    
    // Get actual dependent farmers count based on selected region
    const dependentFarmers = selectedRegion.includes('Punjab') ? 12450 : 
                            selectedRegion.includes('Maharashtra') ? 15680 :
                            selectedRegion.includes('Karnataka') ? 18920 :
                            selectedRegion.includes('Uttar Pradesh') ? 22340 : 8340;
    
    // Dynamic team size and arrival time based on risk and farmer count
    const riskMultiplier = decisionResult.risk >= 0.7 ? 1.5 : decisionResult.risk >= 0.4 ? 1.2 : 1;
    const baseTeamSize = dependentFarmers > 15000 ? 6 : 4;
    const teamSize = Math.round(baseTeamSize * riskMultiplier);
    const pathologists = decisionResult.risk >= 0.7 ? 3 : 2;
    const arrivalHours = decisionResult.risk >= 0.7 ? '2-4' : '4-6';
    
    setDialogMessage({
      type: 'info',
      title: 'Field Verification Team Dispatched',
      message: `Agricultural extension team has been deployed to ${selectedRegion} for on-ground verification.`,
      details: `• Team Size: ${teamSize} agricultural officers + ${pathologists} plant pathologists\n• Departure: Within 2 hours from district headquarters\n• Estimated Arrival: ${arrivalHours} hours (depending on road conditions)\n• Verification Scope: Disease severity assessment, crop damage evaluation, containment feasibility\n• Expected Report: 48 hours after field visit\n• Team Lead: Dr. Priya Singh (Plant Pathology Specialist)\n\nRequest ID: FV-${Date.now()}\nRequested by: Dr. Rajesh Kumar Sharma (DAO-PB-2018-4523)\nTimestamp: ${new Date().toLocaleString('en-IN')}`
    });
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-8 py-6">
        <div>
          <h1 className="text-2xl text-gray-900 mb-1">Containment Decision Control Room</h1>
          <p className="text-sm text-gray-600">AI-assisted containment planning with human oversight</p>
        </div>
      </div>

      {/* Main Content */}
      <div className="p-8">
        <div className="grid grid-cols-3 gap-6">
          {/* Left Panel - Inputs */}
          <div className="col-span-1 space-y-6">
            {/* Input Card */}
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <h2 className="text-gray-900 mb-4 flex items-center gap-2">
                <MapPin className="w-5 h-5 text-[#2f9d58]" />
                Decision Parameters
              </h2>

              <div className="space-y-4">
                {/* Region Selection */}
                <div>
                  <label className="block text-sm text-gray-700 mb-1.5">Region Under Assessment</label>
                  <select
                    value={selectedRegion}
                    onChange={(e) => setSelectedRegion(e.target.value)}
                    aria-label="Region Under Assessment"
                    className="w-full px-3 py-2 border border-gray-300 rounded text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#2f9d58] focus:ring-opacity-30"
                  >
                    {regions.map((region) => (
                      <option key={region} value={region}>{region}</option>
                    ))}
                  </select>
                </div>

                {/* Disease Selection */}
                <div>
                  <label className="block text-sm text-gray-700 mb-1.5">Disease Type</label>
                  <select
                    value={selectedDisease}
                    onChange={(e) => setSelectedDisease(e.target.value)}
                    aria-label="Disease Type"
                    className="w-full px-3 py-2 border border-gray-300 rounded text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#2f9d58] focus:ring-opacity-30"
                  >
                    {diseases.map((disease) => (
                      <option key={disease} value={disease}>{disease}</option>
                    ))}
                  </select>
                </div>

                {/* Severity */}
                <div>
                  <label className="block text-sm text-gray-700 mb-1.5">Disease Severity</label>
                  <div className="flex gap-2">
                    {['Low', 'Medium', 'High', 'Critical'].map((level) => (
                      <button
                        key={level}
                        onClick={() => setSeverity(level)}
                        className={`flex-1 px-3 py-2 rounded text-sm transition-colors ${
                          severity === level
                            ? 'bg-[#2f9d58] text-white'
                            : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                        }`}
                      >
                        {level}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Data Confidence */}
                <div>
                  <label className="block text-sm text-gray-700 mb-1.5">
                    Data Confidence: {dataConfidence}%
                  </label>
                  <input
                    type="range"
                    min="50"
                    max="100"
                    value={dataConfidence}
                    onChange={(e) => setDataConfidence(Number(e.target.value))}
                    aria-label="Data Confidence Level"
                    className="w-full"
                  />
                  <div className="flex justify-between text-xs text-gray-500 mt-1">
                    <span>Field Data</span>
                    <span>Verified</span>
                  </div>
                </div>

                {/* Generate Button */}
                <button
                  onClick={handleGenerateRecommendation}
                  className="w-full bg-[#2f9d58] text-white py-2.5 rounded hover:bg-[#237a3f] transition-colors flex items-center justify-center gap-2"
                >
                  <AlertTriangle className="w-4 h-4" />
                  Generate Containment Recommendation
                </button>
              </div>
            </div>

            {/* Supply Chain Connectivity */}
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <h3 className="text-sm text-gray-900 mb-3">Supply-Chain Connectivity</h3>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-gray-600">Connected Markets:</span>
                  <span className="text-gray-900">
                    {selectedRegion.includes('Punjab') ? '15' : 
                     selectedRegion.includes('Maharashtra') ? '18' :
                     selectedRegion.includes('Karnataka') ? '22' :
                     selectedRegion.includes('Uttar Pradesh') ? '25' : '12'}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Daily Throughput:</span>
                  <span className="text-gray-900">
                    {selectedRegion.includes('Punjab') ? '3,200 MT' : 
                     selectedRegion.includes('Maharashtra') ? '4,100 MT' :
                     selectedRegion.includes('Karnataka') ? '5,800 MT' :
                     selectedRegion.includes('Uttar Pradesh') ? '6,900 MT' : '2,400 MT'}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Dependent Farmers:</span>
                  <span className="text-gray-900">
                    {selectedRegion.includes('Punjab') ? '12,450' : 
                     selectedRegion.includes('Maharashtra') ? '15,680' :
                     selectedRegion.includes('Karnataka') ? '18,920' :
                     selectedRegion.includes('Uttar Pradesh') ? '22,340' : '8,340'}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Right Panel - Recommendation */}
          <div className="col-span-2 space-y-6">
            {!decisionResult ? (
              <div className="bg-white rounded-lg border border-gray-200 p-12 text-center">
                <AlertTriangle className="w-12 h-12 text-gray-400 mx-auto mb-4" />
                <h3 className="text-gray-900 mb-2">No Active Recommendation</h3>
                <p className="text-sm text-gray-600">
                  Configure decision parameters in the left panel and generate a containment recommendation 
                  to view AI-assisted analysis and impact assessment.
                </p>
              </div>
            ) : (
              <div
                style={{
                  marginTop: "24px",
                  padding: "20px",
                  borderRadius: "8px",
                  background: "#f9fafb",
                  border: "1px solid #e5e7eb",
                }}
              >
                <h3 style={{ marginBottom: "12px", color: "#111827" }}>
                  AI Containment Recommendation
                </h3>

                <p>
                  <b>Recommended Action:</b> {decisionResult.action}
                </p>

                <p>
                  <b>Risk Score:</b> 
                  <span style={{
                    color: decisionResult.risk >= 0.7 ? '#dc2626' : 
                           decisionResult.risk >= 0.4 ? '#ea580c' : '#16a34a',
                    fontWeight: 'bold'
                  }}>
                    {decisionResult.risk >= 0.7 ? '🔴' : decisionResult.risk >= 0.4 ? '🟠' : '🟢'} {decisionResult.risk}
                  </span>
                </p>

                <p>
                  <b>Confidence Level:</b> {decisionResult.confidence}
                </p>

                <p>
                  <b>AI Explanation:</b> {decisionResult.explanation}
                </p>

                {/* Action Buttons */}
                <div style={{ marginTop: "20px", display: "flex", gap: "12px", flexWrap: "wrap" }}>
                  <button
                    onClick={handleApproveAndImplement}
                    style={{
                      padding: "10px 16px",
                      backgroundColor: "#16a34a",
                      color: "white",
                      border: "none",
                      borderRadius: "6px",
                      cursor: "pointer",
                      fontSize: "14px",
                      fontWeight: "500"
                    }}
                  >
                    ✅ Approve & Implement
                  </button>
                  <button
                    onClick={handleRecommendForReview}
                    style={{
                      padding: "10px 16px",
                      backgroundColor: "#ea580c",
                      color: "white",
                      border: "none",
                      borderRadius: "6px",
                      cursor: "pointer",
                      fontSize: "14px",
                      fontWeight: "500"
                    }}
                  >
                    📋 Recommend for Review
                  </button>
                  <button
                    onClick={handleRequestFieldVerification}
                    style={{
                      padding: "10px 16px",
                      backgroundColor: "#2563eb",
                      color: "white",
                      border: "none",
                      borderRadius: "6px",
                      cursor: "pointer",
                      fontSize: "14px",
                      fontWeight: "500"
                    }}
                  >
                    🔍 Request Field Verification
                  </button>
                </div>

                {/* Export Button */}
                <div style={{ marginTop: "16px" }}>
                  <button
                    onClick={() => downloadPDF()}
                    style={{
                      padding: "8px 16px",
                      backgroundColor: "#6b7280",
                      color: "white",
                      border: "none",
                      borderRadius: "6px",
                      cursor: "pointer",
                      fontSize: "14px"
                    }}
                  >
                    📄 Download Decision Report
                  </button>
                </div>
              </div>
            )}

            {/* Decision History */}
            {decisionHistory.length > 0 && (
              <div style={{
                marginTop: "24px",
                padding: "20px",
                borderRadius: "8px",
                background: "#f8fafc",
                border: "1px solid #e2e8f0"
              }}>
                <h3 style={{ marginBottom: "16px", color: "#1e293b" }}>
                  📋 Decision History (Last 3)
                </h3>
                <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                  {decisionHistory.map((decision, index) => (
                    <div
                      key={index}
                      style={{
                        padding: "12px",
                        backgroundColor: "white",
                        border: "1px solid #e2e8f0",
                        borderRadius: "6px",
                        fontSize: "13px"
                      }}
                    >
                      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "8px" }}>
                        <span style={{ fontWeight: "bold", color: "#475569" }}>
                          {decision.region} - {decision.disease}
                        </span>
                        <span style={{ color: "#64748b", fontSize: "11px" }}>
                          {decision.timestamp}
                        </span>
                      </div>
                      <div style={{ display: "flex", gap: "16px" }}>
                        <span>
                          Action: <b>{decision.action}</b>
                        </span>
                        <span>
                          Risk: 
                          <span style={{
                            color: decision.risk >= 0.7 ? '#dc2626' : 
                                   decision.risk >= 0.4 ? '#ea580c' : '#16a34a',
                            fontWeight: 'bold'
                          }}>
                            {decision.risk >= 0.7 ? '🔴' : decision.risk >= 0.4 ? '🟠' : '🟢'} {decision.risk}
                          </span>
                        </span>
                        <span>
                          Confidence: <b>{decision.confidence}</b>
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Dialog Message */}
      {dialogMessage && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          {/* Backdrop */}
          <div 
            className="fixed inset-0 bg-black/50 backdrop-blur-sm"
            onClick={() => setDialogMessage(null)}
          />
          
          {/* Dialog Content */}
          <div className="relative bg-white rounded-xl shadow-2xl border-2 border-[#2f9d58] p-8 max-w-lg w-full mx-4 max-h-[80vh] overflow-y-auto">
            {/* Close Button */}
            <button
              onClick={() => setDialogMessage(null)}
              className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 transition-colors"
              aria-label="Close dialog"
            >
              <X className="w-4 h-4" />
            </button>

            {/* Dialog Header */}
            <div className="mb-4">
              <div className="flex items-center gap-3 mb-2">
                {dialogMessage.type === 'success' && <CheckCircle className="w-6 h-6 text-green-600" />}
                {dialogMessage.type === 'warning' && <AlertTriangle className="w-6 h-6 text-amber-600" />}
                {dialogMessage.type === 'info' && <Info className="w-6 h-6 text-blue-600" />}
                <h3 className="text-lg font-semibold text-gray-900">{dialogMessage.title}</h3>
              </div>
              <p className="text-sm text-gray-600">{dialogMessage.message}</p>
            </div>

            {/* Dialog Details */}
            {dialogMessage.details && (
              <div className="mb-6">
                <div className="bg-gray-50 border border-gray-200 rounded-xl p-4">
                  <pre className="text-sm text-gray-700 whitespace-pre-wrap font-mono leading-relaxed">
                    {dialogMessage.details}
                  </pre>
                </div>
              </div>
            )}

            {/* Dialog Actions */}
            <div className="flex gap-3 justify-end">
              <button
                onClick={() => setDialogMessage(null)}
                className="px-6 py-3 text-sm font-medium text-gray-700 bg-white border-2 border-gray-300 rounded-xl hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#2f9d58]/50 transition-all shadow-sm hover:shadow-md"
              >
                Close
              </button>
              <button
                onClick={() => setDialogMessage(null)}
                className={`px-6 py-3 text-sm font-medium text-white border-2 rounded-xl transition-all shadow-sm hover:shadow-md transform hover:scale-105 ${
                  dialogMessage.type === 'success' ? 'bg-green-600 border-green-700 hover:bg-green-700' :
                  dialogMessage.type === 'warning' ? 'bg-amber-600 border-amber-700 hover:bg-amber-700' :
                  'bg-blue-600 border-blue-700 hover:bg-blue-700'
                }`}
              >
                Acknowledge
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

