import React, { useState } from 'react';
import { User, Mail, Phone, Calendar, MapPin, Shield, Briefcase, Award, Clock, FileCheck, Camera, Download, Globe, Send, X, Paperclip, Bold, Italic, Underline, AlignLeft, AlignCenter, AlignRight, TrendingUp, AlertTriangle, CheckCircle, Activity, Zap, Edit2, Save, XCircle } from 'lucide-react';
import LogoutDialog from './LogoutDialog';

interface ProfilePageProps {
  officerData: {
    name: string;
    designation: string;
    region: string;
    employeeId: string;
    department: string;
    email: string;
    phone: string;
    joinDate: string;
  };
  lastLogin: Date | null;
  onLogout: () => void;
  role?: 'officer' | 'field-employee';
}

// Language Context
type Language = 'en' | 'hi';

const translations = {
    en: {
      officerProfile: 'Officer Profile',
      employeeProfile: 'Employee Profile',
      completeInfo: 'Complete employee information and system activity',
      basicInfo: 'Basic Info',
      department: 'Department',
      regionJurisdiction: 'Region Jurisdiction',
      officialEmail: 'Official Email',
      contactNumber: 'Contact Number',
      dateOfJoining: 'Date of Joining',
      lastLogin: 'Last Login',
      systemAccess: 'System Access',
      dashboardAccess: 'Dashboard Access',
      containmentControl: 'Containment Control',
      approvalAuthority: 'Approval Authority',
      reportGeneration: 'Report Generation',
      activityStatistics: 'Activity Statistics',
      recentActivity: 'Recent Activity',
      certificationsTraining: 'Certifications & Training',
      officerAccountability: 'Officer Accountability',
      employeeAccountability: 'Employee Accountability',
      decisionsApproved: 'Decisions Approved',
      casesReviewed: 'Cases Reviewed',
      fieldVerifications: 'Field Verifications',
      reportsSubmitted: 'Reports Submitted',
      tasksCompleted: 'Tasks Completed',
      samplesCollected: 'Samples Collected',
      inspectionsConducted: 'Inspections Conducted',
      reportsGenerated: 'Reports Generated',
      downloadCertificate: 'Download Certificate',
      allActionsLogged: 'All actions are logged for audit',
      systemInformation: 'System Information',
      generatedBy: 'Generated By',
      purpose: 'Purpose',
      verificationInfo: 'Verification Information',
      digitalCopyValid: 'Digital copy is valid for official purposes',
      physicalCertificateAvailable: 'Physical certificate available upon request',
      issuedBy: 'Issued By',
      year: 'Year',
      status: 'Status',
      certificationType: 'Certification Type',
      record: 'Record',
      details: 'Details',
      aiGuide: 'AI Guide',
      getAIGuidance: 'Get AI guidance',
      aiGuideTitle: 'AgriPulseX AI Guide',
      aiGuideSubtitle: 'Your intelligent assistant for officer guidance',
      welcomeToAIGuide: 'Welcome to AI Guide',
      hereToHelp: 'I\'m here to help you with:',
      reportGuidelines: 'Report submission guidelines',
      diseaseProtocols: 'Disease identification protocols',
      containmentProcedures: 'Containment procedures',
      systemNavigation: 'System navigation',
      askPlaceholder: 'Ask me about reports, diseases, containment procedures...',
      send: 'Send',
      poweredByAI: 'Powered by AI • Responses are for guidance purposes only'
    },
    hi: {
      officerProfile: 'अधिकारी प्रोफाइल',
      employeeProfile: 'कर्मचारी प्रोफाइल',
      completeInfo: 'पूर्ण कर्मचारी जानकारी और सिस्टम गतिविधि',
      basicInfo: 'बुनिक सूचना',
      department: 'विभाग',
      regionJurisdiction: 'क्षेत्र अधिकार',
      officialEmail: 'आधिकारिक ईमेल',
      contactNumber: 'संपर्क संख्या',
      dateOfJoining: 'ज्वाइन दिनाख',
      lastLogin: 'अंतिमा लॉगिन',
      systemAccess: 'सिस्टम अभिग',
      dashboardAccess: 'डैशोर्ड अभिग',
      containmentControl: 'नियंत्रण नियंत्रण',
      approvalAuthority: 'अनुमोदन प्राधिकार',
      reportGeneration: 'रिपोर्ट उत्पादन',
      activityStatistics: 'गतिविधि सांख्य',
      recentActivity: 'हाल मौसे गतिविधि',
      certificationsTraining: 'प्रमाणपत्र प्रकार प्रशिक्षण',
      officerAccountability: 'अधिकारी जवाबदारव',
      employeeAccountability: 'कर्मचारी जवाबदारव',
      decisionsApproved: 'निर्णये स्वीकृत',
      casesReviewed: 'मामलों की गई',
      fieldVerifications: 'फील्ड सत्यापन',
      reportsGenerated: 'रिपोर्ट उत्पादन',
      downloadCertificate: 'प्रमाणपत्र डाउनलोड',
      allActionsLogged: 'सभी सभी कार्यों का लेखा-अंकित किया गया',
      systemInformation: 'सिस्टम जानकारी',
      generatedBy: 'द्वारा द्वारा',
      purpose: 'उद्देश',
      verificationInfo: 'सत्यापन की जानकारी',
      digitalCopyValid: 'डिजिटल कॉपी आधिकारिक ईमेल आधिकारिक उद्देशों के लिए आधिकारिक प्रयोजन',
      physicalCertificateAvailable: 'अनुरोदन पर अनुरोदन प्रमाणपत्र उपलब्ध उपलब्ध आवार',
      issuedBy: 'द्वारा द्वारा',
      year: 'वर्ष',
      status: 'स्थिति',
      certificationType: 'प्रमाणपत्र प्रकार',
      record: 'रिकॉर्ड',
      details: 'विवरण',
      aiGuide: 'एआई गाइड',
      getAIGuidance: 'एआई मार्गदर्शन प्राप्त करें',
      aiGuideTitle: 'एग्रीपल्सएक्स एआई गाइड',
      aiGuideSubtitle: 'अधिकारी मार्गदर्शन के लिए आपका बुद्धिमान सहायक',
      welcomeToAIGuide: 'एआई गाइड में आपका स्वागत है',
      hereToHelp: 'मैं आपकी सहायता के लिए यहां हूँ:',
      reportGuidelines: 'रिपोर्ट प्रस्तुति दिशानिर्देश',
      diseaseProtocols: 'रोग पहचान प्रोटोकॉल',
      containmentProcedures: 'नियंत्रण प्रक्रियाएं',
      systemNavigation: 'सिस्टम नेविगेशन',
      askPlaceholder: 'रिपोर्ट, रोग, नियंत्रण प्रक्रियाओं के बारे में पूछें...',
      send: 'भेजें',
      poweredByAI: 'एआई द्वारा संचालित • प्रतिक्रियाएं केवल मार्गदर्शन उद्देश्यों के लिए हैं'
    }
  };

export default function ProfilePage({ officerData, lastLogin, onLogout, role = 'officer' }: ProfilePageProps) {
  const [profileImage, setProfileImage] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const [language, setLanguage] = useState<Language>('en');
  const [showMailCompose, setShowMailCompose] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editedData, setEditedData] = useState({
    name: officerData.name,
    designation: officerData.designation,
    region: officerData.region,
    department: officerData.department,
    email: officerData.email,
    phone: officerData.phone
  });
  const [mailData, setMailData] = useState({
    to: '',
    subject: '',
    message: ''
  });

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString(language === 'hi' ? 'hi-IN' : 'en-IN', { 
      day: '2-digit', 
      month: 'long', 
      year: 'numeric' 
    });
  };

  // Role-based activity statistics
  const officerActivityStats = [
    { label: 'Decisions Approved', value: '47', period: 'Last 12 months' },
    { label: 'Cases Reviewed', value: '132', period: 'Last 12 months' },
    { label: 'Field Verifications', value: '28', period: 'Last 6 months' },
    { label: 'Reports Generated', value: '89', period: 'Last 12 months' }
  ];

  const fieldEmployeeActivityStats = [
    { label: 'Reports Submitted', value: '156', period: 'Last 12 months' },
    { label: 'Tasks Completed', value: '234', period: 'Last 12 months' },
    { label: 'Samples Collected', value: '89', period: 'Last 6 months' },
    { label: 'Inspections Conducted', value: '67', period: 'Last 12 months' }
  ];

  const activityStats = role === 'field-employee' ? fieldEmployeeActivityStats : officerActivityStats;

  const formatLastLogin = (date: Date | null) => {
    if (!date) return 'N/A';
    return date.toLocaleDateString(language === 'hi' ? 'hi-IN' : 'en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    });
  };

  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      // Validate file type
      if (!file.type.startsWith('image/')) {
        alert('Please select an image file (JPG, PNG, etc.)');
        return;
      }
      
      // Validate file size (max 5MB)
      if (file.size > 5 * 1024 * 1024) {
        alert('Image size should be less than 5MB');
        return;
      }

      setUploading(true);
      
      // Create file reader to preview image
      const reader = new FileReader();
      reader.onload = (e) => {
        const result = e.target?.result as string;
        setProfileImage(result);
        setUploading(false);
        
        // Show success message
        alert('Profile picture uploaded successfully!');
      };
      reader.onerror = () => {
        setUploading(false);
        alert('Failed to upload image. Please try again.');
      };
      reader.readAsDataURL(file);
    }
  };

  const triggerFileInput = () => {
    const fileInput = document.getElementById('profile-image-input') as HTMLInputElement;
    fileInput?.click();
  };

  const handleDownloadCertification = (cert: any, index: number) => {
    // Create individual certification content
    const certContent = `
CERTIFICATION RECORD
==================

Officer Name: ${officerData.name}
Employee ID: ${officerData.employeeId}
Department: ${officerData.department}

Generated: ${new Date().toLocaleDateString()}
Download ID: CERT-${index + 1}-${Date.now()}

CERTIFICATION DETAILS
-------------------

${index + 1}. ${cert.name}
   Issued By: ${cert.issued}
   Year: ${cert.year}
   Status: Active • Verified
   Certification Type: Professional Development

VERIFICATION INFORMATION
-----------------------
• This certification is verified by ${cert.issued}
• Record is maintained in the official government database
• Digital copy is valid for official purposes
• Physical certificate available upon request

SYSTEM INFORMATION
------------------
Generated By: AgriPulseX Profile System
System Version: v2.1.0
Purpose: Individual Certification Record

This document certifies that ${officerData.name} has successfully completed 
the ${cert.name} program as issued by ${cert.issued} in ${cert.year}.

For verification inquiries, contact:
${officerData.department}
${officerData.email}
${officerData.phone}
    `.trim();

    // Create a blob with the content
    const blob = new Blob([certContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    
    // Create a temporary link and trigger download
    const link = document.createElement('a');
    link.href = url;
    link.download = `${cert.name.replace(/\s+/g, '_')}_Certification_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up the URL
    URL.revokeObjectURL(url);
  };

  const handleSendMail = () => {
    if (!mailData.to || !mailData.subject || !mailData.message) {
      alert('Please fill in all fields before sending.');
      return;
    }

    // Create mailto link
    const mailtoLink = `mailto:${mailData.to}?subject=${encodeURIComponent(mailData.subject)}&body=${encodeURIComponent(mailData.message)}`;
    window.open(mailtoLink);
    
    // Reset form and close modal
    setMailData({ to: '', subject: '', message: '' });
    setShowMailCompose(false);
    alert('Email client opened with your message!');
  };

  const handleEditToggle = () => {
    if (isEditing) {
      // Cancel editing - reset to original data
      setEditedData({
        name: officerData.name,
        designation: officerData.designation,
        region: officerData.region,
        department: officerData.department,
        email: officerData.email,
        phone: officerData.phone
      });
    }
    setIsEditing(!isEditing);
  };

  const handleInputChange = (field: string, value: string) => {
    setEditedData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleSaveProfile = () => {
    // Validate required fields
    if (!editedData.name || !editedData.email || !editedData.phone) {
      alert('Please fill in all required fields (Name, Email, Phone)');
      return;
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(editedData.email)) {
      alert('Please enter a valid email address');
      return;
    }

    // Validate phone format (basic)
    const phoneRegex = /^[\d\s\-\+\(\)]+$/;
    if (!phoneRegex.test(editedData.phone.replace(/\s/g, ''))) {
      alert('Please enter a valid phone number');
      return;
    }

    // Simulate saving to backend
    console.log('Saving profile data:', editedData);
    
    // Show success message
    alert('Profile updated successfully!');
    
    // In a real app, you would make an API call here:
    // fetch('/api/user/profile', {
    //   method: 'PUT',
    //   headers: { 'Content-Type': 'application/json' },
    //   body: JSON.stringify(editedData)
    // });
    
    setIsEditing(false);
  };

  const officerRecentActivity = [
    { date: '2026-01-02', action: 'Approved Containment', case: 'CNT-2026-001', region: 'Punjab - Amritsar' },
    { date: '2025-12-29', action: 'Field Verification', case: 'CNT-2025-345', region: 'Punjab - Ludhiana' },
    { date: '2025-12-26', action: 'Report Generated', case: 'CNT-2025-340', region: 'Punjab - Patiala' },
    { date: '2025-12-23', action: 'Reviewed Advisory', case: 'CNT-2025-338', region: 'Punjab - Amritsar' },
    { date: '2025-12-20', action: 'Approved Containment', case: 'CNT-2025-335', region: 'Punjab - Bathinda' }
  ];

  const fieldEmployeeRecentActivity = [
    { date: '2026-01-03', action: 'Sample Collection', case: 'SMP-2026-012', region: 'Punjab - Ludhiana' },
    { date: '2026-01-01', action: 'Field Inspection', case: 'INS-2025-089', region: 'Punjab - Amritsar' },
    { date: '2025-12-30', action: 'Report Submitted', case: 'RPT-2025-234', region: 'Punjab - Patiala' },
    { date: '2025-12-28', action: 'Treatment Applied', case: 'TRT-2025-156', region: 'Punjab - Jalandhar' },
    { date: '2025-12-25', action: 'Farm Visit', case: 'VIS-2025-445', region: 'Punjab - Firozpur' }
  ];

  const recentActivity = role === 'field-employee' ? fieldEmployeeRecentActivity : officerRecentActivity;

  const officerCertifications = [
    { name: 'Plant Disease Management Specialist', issued: 'Ministry of Agriculture', year: '2023' },
    { name: 'Supply-Chain Risk Assessment', issued: 'National Institute of Agricultural Extension', year: '2022' },
    { name: 'Decision Intelligence Systems', issued: 'AgriPulseX Training Academy', year: '2024' }
  ];

  const fieldEmployeeCertifications = [
    { name: 'Field Inspection Certification', issued: 'Agricultural Department', year: '2023' },
    { name: 'Sample Collection Training', issued: 'AgriPulseX Field Academy', year: '2024' },
    { name: 'Pesticide Application License', issued: 'Pesticide Control Board', year: '2022' }
  ];

  const certifications = role === 'field-employee' ? fieldEmployeeCertifications : officerCertifications;

  // Performance metrics data
  const officerPerformanceMetrics = {
    responseTime: { value: '2.3 hrs', trend: 'down', change: '-15%' },
    accuracy: { value: '94.2%', trend: 'up', change: '+3.1%' },
    casesHandled: { value: '156', trend: 'up', change: '+12%' },
    farmerSatisfaction: { value: '4.7/5', trend: 'up', change: '+0.3' }
  };

  const fieldEmployeePerformanceMetrics = {
    responseTime: { value: '1.8 hrs', trend: 'down', change: '-20%' },
    accuracy: { value: '91.5%', trend: 'up', change: '+2.8%' },
    tasksCompleted: { value: '234', trend: 'up', change: '+18%' },
    farmerRating: { value: '4.8/5', trend: 'up', change: '+0.4' }
  };

  const performanceMetrics = role === 'field-employee' ? fieldEmployeePerformanceMetrics : officerPerformanceMetrics;

  const regionalAlerts = [
    { type: 'warning', message: 'Late Blight detected in Amritsar region', count: 3, time: '2 hrs ago' },
    { type: 'success', message: 'Containment completed in Ludhiana', count: 1, time: '5 hrs ago' },
    { type: 'info', message: 'Weather advisory issued for Patiala', count: 1, time: '8 hrs ago' }
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-8 py-6">
        <div>
          <h1 className="text-2xl text-gray-900 mb-1">{role === 'field-employee' ? translations[language].employeeProfile : translations[language].officerProfile}</h1>
          <p className="text-sm text-gray-600">{translations[language].completeInfo}</p>
        </div>

        {/* Language Selector */}
        <div className="flex items-center justify-end mb-4">
          <div className="flex items-center gap-2">
            <Globe className="w-4 h-4 text-gray-500" />
            <span className="text-sm text-gray-600">Language:</span>
          </div>
          <select
            value={language}
            onChange={(e) => setLanguage(e.target.value as Language)}
            className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#2f9d58] bg-white"
            title="Select language"
          >
            <option value="en">English</option>
            <option value="hi">हिंदी</option>
          </select>
        </div>
      </div>

      {/* Main Content */}
      <div className="p-8">
        <div className="grid grid-cols-3 gap-6">
          {/* Left Column - Profile Info */}
          <div className="col-span-1 space-y-6">
            {/* Basic Info Card */}
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <div className="text-center mb-6">
                <div className="relative inline-block">
                  <div className="w-24 h-24 bg-gray-200 rounded-full flex items-center justify-center mx-auto mb-4 overflow-hidden">
                    {profileImage ? (
                      <img 
                        src={profileImage} 
                        alt="Profile" 
                        className="w-full h-full object-cover"
                      />
                    ) : (
                      <User className="w-12 h-12 text-gray-400" />
                    )}
                  </div>
                  <button
                    onClick={triggerFileInput}
                    className="absolute bottom-2 right-0 w-8 h-8 bg-[#2f9d58] rounded-full flex items-center justify-center text-white hover:bg-[#237a3f] transition-colors shadow-sm"
                    title="Upload profile picture"
                  >
                    {uploading ? (
                      <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    ) : (
                      <Camera className="w-4 h-4" />
                    )}
                  </button>
                </div>
                
                {/* Name Display with Edit */}
                <div className="flex items-center justify-center gap-2 mb-1">
                  {isEditing ? (
                    <input
                      type="text"
                      value={editedData.name}
                      onChange={(e) => handleInputChange('name', e.target.value)}
                      className="text-xl text-center text-gray-900 bg-white border border-gray-300 rounded px-2 py-1 focus:outline-none focus:ring-2 focus:ring-[#2f9d58]"
                      placeholder="Enter your name"
                    />
                  ) : (
                    <h2 className="text-xl text-gray-900">{editedData.name}</h2>
                  )}
                </div>
                
                {/* Designation Display with Edit */}
                <div className="flex items-center justify-center gap-2 mb-3">
                  {isEditing ? (
                    <input
                      type="text"
                      value={editedData.designation}
                      onChange={(e) => handleInputChange('designation', e.target.value)}
                      className="text-sm text-center text-gray-600 bg-white border border-gray-300 rounded px-2 py-1 focus:outline-none focus:ring-2 focus:ring-[#2f9d58]"
                      placeholder="Enter your designation"
                    />
                  ) : (
                    <p className="text-sm text-gray-600">{editedData.designation}</p>
                  )}
                </div>
                
                <div className="mt-3 px-3 py-1.5 bg-blue-100 text-blue-700 rounded-full text-xs inline-block">
                  {officerData.employeeId}
                </div>
                
                {/* Edit/Save Button */}
                <div className="mt-4 flex justify-center gap-2">
                  {isEditing ? (
                    <>
                      <button
                        onClick={handleSaveProfile}
                        className="flex items-center gap-1.5 px-4 py-2 bg-green-600 text-white rounded text-xs hover:bg-green-700 transition-colors shadow-sm"
                        title="Save profile changes"
                      >
                        <Save className="w-3 h-3" />
                        Save
                      </button>
                      <button
                        onClick={handleEditToggle}
                        className="flex items-center gap-1.5 px-4 py-2 bg-gray-600 text-white rounded text-xs hover:bg-gray-700 transition-colors shadow-sm"
                        title="Cancel editing"
                      >
                        <XCircle className="w-3 h-3" />
                        Cancel
                      </button>
                    </>
                  ) : (
                    <>
                      <button
                        onClick={handleEditToggle}
                        className="flex items-center gap-1.5 px-4 py-2 bg-[#2f9d58] text-white rounded text-xs hover:bg-[#237a3f] transition-colors shadow-sm"
                        title="Edit profile"
                      >
                        <Edit2 className="w-3 h-3" />
                        Edit Profile
                      </button>
                    </>
                  )}
                </div>
              </div>

              {/* Hidden file input */}
              <label htmlFor="profile-image-input" className="sr-only">
                Upload profile picture
              </label>
              <input
                id="profile-image-input"
                type="file"
                accept="image/*"
                onChange={handleImageUpload}
                className="hidden"
                aria-label="Upload profile picture"
                title="Upload profile picture"
              />

              <div className="space-y-4 pt-4 border-t border-gray-200">
                <div className="flex items-start gap-3">
                  <Briefcase className="w-4 h-4 text-gray-500 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <div className="text-xs text-gray-600 mb-0.5">{translations[language].department}</div>
                    {isEditing ? (
                      <input
                        type="text"
                        value={editedData.department}
                        onChange={(e) => handleInputChange('department', e.target.value)}
                        className="text-sm text-gray-900 bg-white border border-gray-300 rounded px-2 py-1 focus:outline-none focus:ring-2 focus:ring-[#2f9d58] w-full"
                        placeholder="Enter your department"
                      />
                    ) : (
                      <div className="text-sm text-gray-900">{editedData.department}</div>
                    )}
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <MapPin className="w-4 h-4 text-gray-500 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <div className="text-xs text-gray-600 mb-0.5">{translations[language].regionJurisdiction}</div>
                    {isEditing ? (
                      <input
                        type="text"
                        value={editedData.region}
                        onChange={(e) => handleInputChange('region', e.target.value)}
                        className="text-sm text-gray-900 bg-white border border-gray-300 rounded px-2 py-1 focus:outline-none focus:ring-2 focus:ring-[#2f9d58] w-full"
                        placeholder="Enter your region"
                      />
                    ) : (
                      <div className="text-sm text-gray-900">{editedData.region}</div>
                    )}
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <Mail className="w-4 h-4 text-gray-500 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <div className="text-xs text-gray-600 mb-0.5">{translations[language].officialEmail}</div>
                    {isEditing ? (
                      <input
                        type="email"
                        value={editedData.email}
                        onChange={(e) => handleInputChange('email', e.target.value)}
                        className="text-sm text-gray-900 bg-white border border-gray-300 rounded px-2 py-1 focus:outline-none focus:ring-2 focus:ring-[#2f9d58] w-full"
                        placeholder="Enter your email"
                      />
                    ) : (
                      <div className="text-sm text-gray-900 break-all">{editedData.email}</div>
                    )}
                    {!isEditing && (
                      <button
                        onClick={() => setShowMailCompose(true)}
                        className="mt-2 flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 text-white rounded text-xs hover:bg-blue-700 transition-colors shadow-sm"
                        title="Compose new email"
                      >
                        <Mail className="w-3 h-3" />
                        Compose Mail
                      </button>
                    )}
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <Phone className="w-4 h-4 text-gray-500 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <div className="text-xs text-gray-600 mb-0.5">{translations[language].contactNumber}</div>
                    {isEditing ? (
                      <input
                        type="tel"
                        value={editedData.phone}
                        onChange={(e) => handleInputChange('phone', e.target.value)}
                        className="text-sm text-gray-900 bg-white border border-gray-300 rounded px-2 py-1 focus:outline-none focus:ring-2 focus:ring-[#2f9d58] w-full"
                        placeholder="Enter your phone number"
                      />
                    ) : (
                      <div className="text-sm text-gray-900">{editedData.phone}</div>
                    )}
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <Calendar className="w-4 h-4 text-gray-500 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <div className="text-xs text-gray-600 mb-0.5">{translations[language].dateOfJoining}</div>
                    <div className="text-sm text-gray-900">{formatDate(officerData.joinDate)}</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <Clock className="w-4 h-4 text-gray-500 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <div className="text-xs text-gray-600 mb-0.5">Last Login</div>
                    <div className="text-sm text-gray-900">{formatLastLogin(lastLogin)}</div>
                  </div>
                </div>
              </div>
            </div>

            {/* System Access */}
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <h3 className="text-gray-900 mb-4 flex items-center gap-2">
                <Shield className="w-5 h-5 text-[#2f9d58]" />
                {translations[language].systemAccess}
              </h3>
              <div className="space-y-3">
                {role === 'field-employee' ? (
                  <>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">Field Dashboard:</span>
                      <span className="text-green-700">Granted</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">Report Submission:</span>
                      <span className="text-green-700">Granted</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">Sample Collection:</span>
                      <span className="text-green-700">Authorized</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">Mobile Access:</span>
                      <span className="text-green-700">Enabled</span>
                    </div>
                  </>
                ) : (
                  <>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">{translations[language].dashboardAccess}:</span>
                      <span className="text-green-700">Granted</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">{translations[language].containmentControl}:</span>
                      <span className="text-green-700">Granted</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">{translations[language].approvalAuthority}:</span>
                      <span className="text-green-700">Authorized</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">{translations[language].reportGeneration}:</span>
                      <span className="text-green-700">Granted</span>
                    </div>
                  </>
                )}
              </div>
              <div className="mt-4 pt-4 border-t border-gray-200">
                <div className="flex items-center gap-2 text-xs text-amber-700">
                  <div className="w-1.5 h-1.5 rounded-full bg-amber-600"></div>
                  <span>All actions are logged for audit</span>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column - Activity and Stats */}
          <div className="col-span-2 space-y-6">
            {/* Activity Statistics */}
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <h3 className="text-gray-900 mb-4 flex items-center gap-2">
                <Award className="w-5 h-5 text-[#2f9d58]" />
                {role === 'field-employee' ? translations[language].employeeAccountability : translations[language].officerAccountability}
              </h3>
              <div className="grid grid-cols-2 gap-4">
                {activityStats.map((stat, index) => (
                  <div key={index} className="p-4 bg-gray-50 rounded border border-gray-200">
                    <div className="text-2xl text-gray-900 mb-1">{stat.value}</div>
                    <div className="text-sm text-gray-700 mb-1">{stat.label}</div>
                    <div className="text-xs text-gray-500">{stat.period}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Recent Activity */}
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <h2 className="text-gray-900 mb-4 flex items-center gap-2">
                <Clock className="w-5 h-5 text-[#2f9d58]" />
                Recent Activity
              </h2>
              <div className="space-y-3">
                {recentActivity.map((activity, index) => (
                  <div key={index} className="flex items-start gap-4 p-3 bg-gray-50 rounded">
                    <div className="text-xs text-gray-600 w-24 flex-shrink-0 mt-0.5">{activity.date}</div>
                    <div className="flex-1">
                      <div className="text-sm text-gray-900 mb-0.5">{activity.action}</div>
                      <div className="text-xs text-gray-600">
                        {activity.case} • {activity.region}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Performance Dashboard */}
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <h2 className="text-gray-900 mb-4 flex items-center gap-2">
                <Activity className="w-5 h-5 text-[#2f9d58]" />
                Performance Dashboard
              </h2>
              
              {/* Key Metrics Grid */}
              <div className="grid grid-cols-2 gap-4 mb-6">
                {Object.entries(performanceMetrics).map(([key, metric]) => (
                  <div key={key} className="p-4 bg-gray-50 rounded-lg border border-gray-200">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs text-gray-600">
                        {role === 'field-employee' ? (
                          key === 'responseTime' ? 'Response Time' :
                          key === 'accuracy' ? 'Accuracy' :
                          key === 'tasksCompleted' ? 'Tasks Completed' :
                          key === 'farmerRating' ? 'Farmer Rating' : key
                        ) : (
                          key === 'responseTime' ? 'Response Time' :
                          key === 'accuracy' ? 'Accuracy' :
                          key === 'casesHandled' ? 'Cases Handled' :
                          key === 'farmerSatisfaction' ? 'Farmer Satisfaction' : key
                        )}
                      </span>
                      <div className={`flex items-center gap-1 text-xs ${
                        metric.trend === 'up' ? 'text-green-600' : 'text-red-600'
                      }`}>
                        {metric.trend === 'up' ? (
                          <TrendingUp className="w-3 h-3" />
                        ) : (
                          <TrendingUp className="w-3 h-3 rotate-180" />
                        )}
                        {metric.change}
                      </div>
                    </div>
                    <div className="text-xl text-gray-900 font-semibold">{metric.value}</div>
                  </div>
                ))}
              </div>

              {/* Regional Alerts */}
              <div className="border-t border-gray-200 pt-4">
                <h3 className="text-sm text-gray-900 mb-3 flex items-center gap-2">
                  <Zap className="w-4 h-4 text-amber-500" />
                  Regional Alerts
                </h3>
                <div className="space-y-2">
                  {regionalAlerts.map((alert, index) => (
                    <div key={index} className={`flex items-start gap-3 p-3 rounded-lg ${
                      alert.type === 'warning' ? 'bg-amber-50 border border-amber-200' :
                      alert.type === 'success' ? 'bg-green-50 border border-green-200' :
                      'bg-blue-50 border border-blue-200'
                    }`}>
                      <div className="flex-shrink-0 mt-0.5">
                        {alert.type === 'warning' ? (
                          <AlertTriangle className="w-4 h-4 text-amber-600" />
                        ) : alert.type === 'success' ? (
                          <CheckCircle className="w-4 h-4 text-green-600" />
                        ) : (
                          <Activity className="w-4 h-4 text-blue-600" />
                        )}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="text-sm text-gray-900">{alert.message}</div>
                        <div className="text-xs text-gray-500 mt-1">
                          {alert.count} case{alert.count > 1 ? 's' : ''} • {alert.time}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Certifications */}
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <h2 className="text-gray-900 mb-4 flex items-center gap-2">
                <FileCheck className="w-5 h-5 text-[#2f9d58]" />
                Certifications & Training
              </h2>
              <div className="space-y-3">
                {certifications.map((cert, index) => (
                  <div key={index} className="p-4 border border-gray-200 rounded hover:border-[#2f9d58] transition-colors">
                    <div className="flex items-start justify-between mb-2">
                      <div className="flex-1">
                        <div className="text-sm text-gray-900 mb-1">{cert.name}</div>
                        <div className="text-xs text-gray-600">
                          Issued by {cert.issued} • {cert.year}
                        </div>
                      </div>
                      <button
                        onClick={() => handleDownloadCertification(cert, index)}
                        className="flex items-center gap-1.5 px-2.5 py-1.5 bg-[#2f9d58] text-white rounded text-xs hover:bg-[#237a3f] transition-colors shadow-sm"
                        title={`Download ${cert.name} certificate`}
                      >
                        <Download className="w-3 h-3" />
                        Download
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Accountability Notice */}
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
              <div className="flex items-start gap-3">
                <Shield className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm text-amber-900">
                    <strong>Officer Accountability:</strong> As an authorized user of AgriPulseX, you are responsible 
                    for all decisions and actions taken through this system. Your profile information and activity logs 
                    are maintained for institutional audit, policy review, and ministerial oversight in accordance with 
                    government accountability standards.
                  </p>
                </div>
              </div>
            </div>

            {/* Logout Button */}
            <div className="flex justify-center pt-6 space-x-4">
              {/* Test Simple Logout Button */}
              <button 
                onClick={() => {
                  console.log('Simple logout button clicked');
                  onLogout();
                }}
                className="flex items-center gap-2 px-6 py-3 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors shadow-md hover:shadow-lg"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                </svg>
                <span className="font-medium">Simple Logout</span>
              </button>
              
              <LogoutDialog onLogout={onLogout}>
                <button className="flex items-center gap-2 px-6 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors shadow-md hover:shadow-lg">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                  </svg>
                  <span className="font-medium">Secure Logout</span>
                </button>
              </LogoutDialog>
            </div>
          </div>
        </div>
      </div>

      {/* Mail Compose Modal */}
      {showMailCompose && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col">
            {/* Gmail-style Header */}
            <div className="bg-gray-100 border-b border-gray-300 px-4 py-3 flex items-center justify-between rounded-t-lg">
              <h2 className="text-lg font-medium text-gray-800">New Message</h2>
              <button
                onClick={() => setShowMailCompose(false)}
                className="text-gray-500 hover:text-gray-700 transition-colors"
                aria-label="Close mail compose window"
                title="Close mail compose window"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Mail Form */}
            <div className="flex-1 overflow-y-auto">
              <div className="border-b border-gray-200">
                <div className="flex items-center px-4 py-2">
                  <label className="text-sm text-gray-600 w-16">To:</label>
                  <input
                    type="email"
                    value={mailData.to}
                    onChange={(e) => setMailData({ ...mailData, to: e.target.value })}
                    className="flex-1 px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 rounded"
                    placeholder="Recipients"
                  />
                </div>
                <div className="flex items-center px-4 py-2 border-t border-gray-100">
                  <label className="text-sm text-gray-600 w-16">Subject:</label>
                  <input
                    type="text"
                    value={mailData.subject}
                    onChange={(e) => setMailData({ ...mailData, subject: e.target.value })}
                    className="flex-1 px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 rounded"
                    placeholder="Subject"
                  />
                </div>
              </div>

              {/* Gmail-style Toolbar */}
              <div className="border-b border-gray-200 px-4 py-2 flex items-center gap-2">
                <button className="p-1.5 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors" title="Bold">
                  <Bold className="w-4 h-4" />
                </button>
                <button className="p-1.5 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors" title="Italic">
                  <Italic className="w-4 h-4" />
                </button>
                <button className="p-1.5 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors" title="Underline">
                  <Underline className="w-4 h-4" />
                </button>
                <div className="w-px h-4 bg-gray-300 mx-1"></div>
                <button className="p-1.5 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors" title="Attach file">
                  <Paperclip className="w-4 h-4" />
                </button>
                <div className="w-px h-4 bg-gray-300 mx-1"></div>
                <button className="p-1.5 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors" title="Align left">
                  <AlignLeft className="w-4 h-4" />
                </button>
                <button className="p-1.5 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors" title="Align center">
                  <AlignCenter className="w-4 h-4" />
                </button>
                <button className="p-1.5 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors" title="Align right">
                  <AlignRight className="w-4 h-4" />
                </button>
              </div>

              {/* Message Body */}
              <div className="px-4 py-3">
                <textarea
                  value={mailData.message}
                  onChange={(e) => setMailData({ ...mailData, message: e.target.value })}
                  className="w-full h-64 px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                  placeholder="Compose your message..."
                />
              </div>
            </div>

            {/* Gmail-style Footer */}
            <div className="border-t border-gray-200 px-4 py-3 flex items-center justify-between bg-gray-50 rounded-b-lg">
              <button
                onClick={handleSendMail}
                className="flex items-center gap-2 px-6 py-2 bg-blue-600 text-white text-sm font-medium rounded hover:bg-blue-700 transition-colors shadow-sm"
              >
                <Send className="w-4 h-4" />
                Send
              </button>
              <div className="flex items-center gap-3 text-xs text-gray-500">
                <button 
                  className="hover:text-gray-700 transition-colors" 
                  title="Discard message"
                  aria-label="Discard message"
                  onClick={() => {
                    setMailData({ to: '', subject: '', message: '' });
                    setShowMailCompose(false);
                  }}
                >
                  Discard
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

